name = 'Mediakit'
version = '0.5.3'
description = 'Download YouTube videos fast, directly from the command line'
author = 'Diego Aquino'
author_email = 'diegocruzdeaquino@gmail.com'
url = 'https://github.com/diego-aquino/mediakit'
download_url = 'https://github.com/diego-aquino/mediakit/archive/v0.5.3.tar.gz'
license = 'MIT'
copyright = 'Copyright 2021 Diego Aquino'

temp_filename = 'mediakit_temp'
